### ISSUE TITLE
Running Annovar on a merged VCF

### ISSUE THREAD

**Issue by jfnavarro** [umich-brcf-bioinf/Jacquard#5]
Hi! 

I successfuly merged VCF files from different variant callers (Mutec2, Varscan, Somatic Sniper and Strelka2) prior translation of the callers that are compatible. However, when I tried to annotate the merged VCF with Annovar I got the following error:

`Error: invalid record in VCF file: the GT specifier is not present in the FORMAT string:`

Is the output format of the merged VCF incompatible with Annovar when translations have been performed? If I skip the translation I can use Annovar without a problem. 

Best,
Jose

**Comment by cgates** [comment]
Hi Jose,
I'm not 100% sure, but my guess is that Annovar assumes that there is a GT format field for each variant line. (That's a pretty reasonable assumption, since Annovar potentially must choose which of multiple variants at that locus it should consider when predicting impact.) Since you merged the data you could try renaming one of the existing genotype fields (e.g. JQ_VS_GT) to "GT". \If you "summarized" the merged data you could rename JQ_SUMMARY_HC_GT to "GT". Something like this:
sed 's/JQ_SUMMARY_HC_GT/GT/g' summarized.vcf > summarized_GT.vcf
and then annotating "summarized_GT.vcf".
Does that make sense?
Best,
cg

**Comment by cgates** [comment]
Hi Jose,
Wondered if you had a chance to try the workaround above? Or if you were able to resolve another way?
Best,
cg

**Comment by jfnavarro** [comment]
Hi Chris, 

Sorry for the delay getting back to you. 

I tried renaming "JQ_VS_GT", "JQ_MT_GT" and "JQ_SK_GT" to "GT" but then Annovar complained that multiple GT specifiers were present in the FORMAT field. I think this trick would only work if there is only one caller. 

Best,
Jose

**Comment by cgates** [comment]
Hi Jose,
Yes, you are right; I'm sorry I didn't make that clear above. If you run the `summarize` command on the merged VCF, Jacquard will emit a VCF containing a JQ_SUMMARY_HC_GT format field (based on majority votes across callers which reported a variant); then you could transform that field as described above. (That would work for the the supported variant callers.)
Best,
cg

**Comment by jfnavarro** [comment]
Hi Chris, 

Of course you were meaning the summarized one. I had not thought about it even though I was familiar with the summarize command and what it does.  So yeah, using sed to replace the JQ_SUMMARY_HC_GT string by GT does the job and Annovar runs without a problem. May be worth adding an entry in the documentation about this? 

In my personal case I need to implement a variant caller transform for somatic sniper in order to be able to integrate jacquard in our workflow. I plan on doing this as soon as I find some time. I will get back you then! 

Best,
Jose

**Comment by cgates** [comment]
Hi Jose,
Great news and good thought on revising the doc. I will put this on the roadmap.
Good luck with the Somatic Sniper transform. Please let me know if you have questions or I can help.
Best,
cg
